name: React Native Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Install JDK
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 5: Install Android SDK
      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      # Step 6: Grant permission to Gradle wrapper
      - name: Grant execute permission to Gradle
        run: chmod +x ./android/gradlew
      
      # Step 7: Clean and build React Native Android app
      - name: Build React Native APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Clear Cache
        run: rm -rf ~/.npm ~/.cache

      # Step 8: Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
      
      # Step 9 : Send APK to WhatsApp
      - name: Send APK to WhatsApp
        run: |
          curl 'https://api.twilio.com/2010-04-01/Accounts/${{ secrets.TWILIO_ACCOUNT_SID }}/Messages.json' -X POST \
          --data-urlencode 'To=whatsapp:+919309793969' \
          --data-urlencode 'From=whatsapp:+14155238886' \
          --data-urlencode "Body=Download the latest APK: https://github.com/yeshudeshmukh/ci-cd/actions/runs/13876470097/artifacts/2758397926" \
          -u ${{ secrets.TWILIO_ACCOUNT_SID }}:${{ secrets.TWILIO_AUTH_TOKEN }}
            

          
          

          
